image: maven:3-jdk-8

variables: 
  MAVEN_CLI_OPTS: "-f com.zazuko.rdfmapping.dsl.parent --batch-mode"

stages: 
  - package

package: 
  stage: package
  only: 
    - master
  script: 
    - "mvn $MAVEN_CLI_OPTS package"
    - "ls -l com.zazuko.rdfmapping.dsl.parent/com.zazuko.rdfmapping.dsl.repository/target/"