image: maven:3-jdk-11

before_script:
  - apt-get update -qq && apt-get install -y -qq python-pip && pip install -q s3cmd

default:
  tags:
    - kubernetes
  
variables: 
  MAVEN_CLI_OPTS: "-f com.zazuko.rdfmapping.dsl.parent --batch-mode"

stages: 
  - package
  - publish

package: 
  stage: package
  only: 
    - master
    - tags
  except:
    - composite
    - issue_115_shapes
    - 1.0.0_shapes
  script: 
    - "mvn $MAVEN_CLI_OPTS package"
    - "ls -l com.zazuko.rdfmapping.dsl.parent/com.zazuko.rdfmapping.dsl.repository/target/"
  artifacts:
    paths:
      - com.zazuko.rdfmapping.dsl.parent/com.zazuko.rdfmapping.dsl.repository/target/
    expire_in: 60 minutes
    
package-shapes: 
  stage: package
  only: 
    - issue_115_shapes
  script: 
    - "mvn $MAVEN_CLI_OPTS package"
    - "ls -l com.zazuko.rdfmapping.dsl.parent/com.zazuko.rdfmapping.dsl.repository/target/"
  artifacts:
    paths:
      - com.zazuko.rdfmapping.dsl.parent/com.zazuko.rdfmapping.dsl.repository/target/
    expire_in: 60 minutes


s3-releases:
  stage: publish
  only:
    - master
    - tags
  except:
    - composite
    - issue_115_shapes
    - 1.0.0_shapes
  script: 
    - s3cmd -c config/s3cmd sync --acl-public --delete-removed com.zazuko.rdfmapping.dsl.parent/com.zazuko.rdfmapping.dsl.repository/target/repository/ s3://zazuko-download/rdf-mapping-dsl/releases/$CI_COMMIT_TAG/

s3-releases-shapes:
  stage: publish
  only:
    - issue_115_shapes
  script: 
    - s3cmd -c config/s3cmd sync --acl-public --delete-removed com.zazuko.rdfmapping.dsl.parent/com.zazuko.rdfmapping.dsl.repository/target/repository/ s3://zazuko-download/xrm-shacl-prototype/releases/latest/

s3-updates-composite:
  stage: publish
  only:
    - composite
  script: 
    - s3cmd -c config/s3cmd sync --acl-public --delete-removed com.zazuko.rdfmapping.dsl.parent/com.zazuko.rdfmapping.dsl.repository-composite/updates/ s3://zazuko-download/rdf-mapping-dsl/updates/
