/*
 * generated by Xtext 2.25.0
 */
package com.zazuko.rdfmapping.dsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.outline.impl.DocumentRootNode;

import com.zazuko.rdfmapping.dsl.rdfMapping.Mapping;
import com.zazuko.rdfmapping.dsl.rdfMapping.Prefix;
import com.zazuko.rdfmapping.dsl.rdfMapping.Referenceable;
import com.zazuko.rdfmapping.dsl.rdfMapping.TemplateDeclaration;
import com.zazuko.rdfmapping.dsl.rdfMapping.TemplateValuedTerm;
import com.zazuko.rdfmapping.dsl.rdfMapping.Vocabulary;

/**
 * Customization of the default outline structure.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class RdfMappingOutlineTreeProvider extends DefaultOutlineTreeProvider {

	protected void _createChildren(DocumentRootNode parentNode, Mapping mapping) {
		createNode(parentNode, mapping.getSubjectIriMapping());
	}

	protected void _createChildren(DocumentRootNode parentNode, Vocabulary v) {
		createNode(parentNode, v.getPrefix());
	}

	protected void _createNode(IOutlineNode parentNode, Prefix modelElement) {

	}

	protected void _createNode(IOutlineNode parentNode, TemplateValuedTerm modelElement) {

	}

	protected boolean _isLeaf(TemplateDeclaration it) {
		return true;
	}

	protected boolean _isLeaf(Referenceable it) {
		return true;
	}

}
