/*
 * generated by Xtext 2.18.0
 */
package com.zazuko.rdfmapping.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RdfMappingStandaloneSetup extends RdfMappingStandaloneSetupGenerated {

	def static void doSetup() {
		new RdfMappingStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
