/*
 * generated by Xtext 2.25.0
 */
package com.zazuko.rdfmapping.dsl.formatting2;

import org.eclipse.xtext.formatting2.AbstractJavaFormatter;
import org.eclipse.xtext.formatting2.IFormattableDocument;

import com.zazuko.rdfmapping.dsl.rdfMapping.Domainmodel;
import com.zazuko.rdfmapping.dsl.rdfMapping.LanguageTagDefinition;

public class RdfMappingFormatter extends AbstractJavaFormatter {

	protected void format(Domainmodel domainmodel, IFormattableDocument doc) {
		throw new RuntimeException("use RealRdfMappingFormatter.xtend");
	}

	protected void format(LanguageTagDefinition languageTagDefinition, IFormattableDocument doc) {
		throw new RuntimeException("use RealRdfMappingFormatter.xtend");
	}
	
	// TODO: implement for SourceGroup, LogicalSource, Referenceable, DialectGroup, DialectGroupDescription, XmlNamespaceExtension, Vocabulary, RdfProperty, RdfClass, Datatype, TemplateDeclaration, Mapping, PredicateObjectMapping, ReferenceValuedTerm, MultiReferenceValuedTerm, TemplateValuedTerm, OmniMap
}
