/*
 * generated by Xtext 2.25.0
 */
package com.zazuko.rdfmapping.dsl.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import com.google.inject.Inject;
import com.zazuko.rdfmapping.dsl.common.RdfMappingConstants;
import com.zazuko.rdfmapping.dsl.rdfMapping.LanguageTagDefinition;
import com.zazuko.rdfmapping.dsl.rdfMapping.PredicateObjectMapping;
import com.zazuko.rdfmapping.dsl.rdfMapping.Vocabulary;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class RdfMappingLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public RdfMappingLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}
	
	public String text(PredicateObjectMapping it) {
		Vocabulary vocab = (Vocabulary) it.getProperty().eContainer();
		return vocab.getName() + RdfMappingConstants.TOKEN_QNAME_SEPARATOR_RDFPREFIX + it.getProperty().getName();
	}
	
	public String text(LanguageTagDefinition it) {
		return "language-tags";
	}
}
