/*
 * generated by Xtext 2.18.0
 */
package com.zazuko.rdfmapping.dsl.tests

import com.google.inject.Inject
import com.zazuko.rdfmapping.dsl.rdfMapping.Domainmodel
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(RdfMappingInjectorProvider)
class RdfMappingParsingTest {
	@Inject
	ParseHelper<Domainmodel> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			logical-source city {
				type csv
				source "http://www.example.com/City.csv"
				
				referenceables
					continent
					country
					city
			}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
